[package]
name = "k10s-map"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
testing = []
bench-alloc = []

[dependencies]
k10s-atlas.workspace = true
k10s-core.workspace = true
gpui.workspace = true
arc-swap.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
k10s-atlas = { workspace = true, features = ["testing"] }
k10s-clustergen.workspace = true
stats_alloc = "0.1.10"

[[bench]]
name = "walk"
harness = false
required-features = ["testing"]
