[package]
name = "k10s-data"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
k10s-core.workspace = true
kube.workspace = true
k8s-openapi.workspace = true
tokio.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
k10s-world.workspace = true
http = "1"
tower = { version = "0.5", features = ["util"] }
