[package]
name = "k10s-world"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
k10s-core.workspace = true
k10s-clustergen.workspace = true
bevy_ecs.workspace = true
crossbeam-channel.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[[bench]]
name = "publish"
harness = false

